server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.26:3306/tensquare_base?characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: zd
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true #格式化sql